<?php
	require_once("./include/header.php");

	require_once("./template/content_pre.php");
	
?>


<div id="mainContainer">

	<div id="mainContent">

	<h1 class="page-title">Impressum</h1>
		<div id="pageCont">

			<div class='article'><h1>Angaben gem&auml;&szlig; &sect; 5 TMG:</h1>
			<p>Ilja Rozhko<br /> Ernst-Abbe Weg 14<br /> 40589 D&uuml;sseldorf</p>
			<h2>Kontakt:</h2>
			<p>Telefon:&nbsp;+49 (0) 15150757125</p>
			<p>E-Mail: admin [(at)] irworks [(dot/Punkt)] de</p>
			<p>&nbsp;</p>
			<p>Quelle:&nbsp;<em>Erstellt durch den Impressum Generator von&nbsp;<a href="http://www.e-recht24.de/">e-recht24.de</a></em></p>
			<h2>Haftungsausschluss:</h2>
			<p><strong>Haftung f&uuml;r Inhalte</strong></p>
			<p>Die Inhalte unserer Seiten wurden mit gr&ouml;&szlig;ter Sorgfalt erstellt.<br /> F&uuml;r die Richtigkeit, Vollst&auml;ndigkeit und Aktualit&auml;t der Inhalte<br /> k&ouml;nnen wir jedoch keine Gew&auml;hr &uuml;bernehmen. Als Diensteanbieter sind wir gem&auml;&szlig; &sect; 7 Abs.1 TMG f&uuml;r<br /> eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich.<br /> Nach &sect;&sect; 8 bis 10 TMG sind wir als Diensteanbieter jedoch nicht<br /> verpflichtet, &uuml;bermittelte oder gespeicherte fremde Informationen zu<br /> &uuml;berwachen oder nach Umst&auml;nden zu forschen, die auf eine rechtswidrige<br /> T&auml;tigkeit hinweisen. Verpflichtungen zur Entfernung oder Sperrung der<br /> Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon<br /> unber&uuml;hrt. Eine diesbez&uuml;gliche Haftung ist jedoch erst ab dem<br /> Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung m&ouml;glich. Bei<br /> Bekanntwerden von entsprechenden Rechtsverletzungen werden wir diese Inhalte<br /> umgehend entfernen.</p>
			<p><strong>Haftung f&uuml;r Links</strong></p>
			<p>Unser Angebot enth&auml;lt Links zu externen Webseiten Dritter, auf deren<br /> Inhalte wir keinen Einfluss haben. Deshalb k&ouml;nnen wir f&uuml;r diese<br /> fremden Inhalte auch keine Gew&auml;hr &uuml;bernehmen. F&uuml;r die Inhalte<br /> der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der<br /> Seiten verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der Verlinkung<br /> auf m&ouml;gliche Rechtsverst&ouml;&szlig;e &uuml;berpr&uuml;ft. Rechtswidrige<br /> Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar. Eine permanente<br /> inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte<br /> einer Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen<br /> werden wir derartige Links umgehend entfernen.</p>
			<p><strong>Urheberrecht</strong></p>
			<p>Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten<br /> unterliegen dem deutschen Urheberrecht. Die Vervielf&auml;ltigung, Bearbeitung, Verbreitung und<br /> jede Art der Verwertung au&szlig;erhalb der Grenzen des Urheberrechtes bed&uuml;rfen<br /> der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers. Downloads<br /> und Kopien dieser Seite sind nur f&uuml;r den privaten, nicht kommerziellen<br /> Gebrauch gestattet. Soweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt wurden,<br /> werden die Urheberrechte Dritter beachtet. Insbesondere werden Inhalte Dritter als solche<br /> gekennzeichnet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam werden, bitten wir um einen entsprechenden Hinweis.<br /> Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Inhalte umgehend entfernen.</p>
			<p><strong>Datenschutz</strong></p>
			<p>Die Nutzung unserer Webseite ist in der Regel ohne Angabe personenbezogener Daten m&ouml;glich. Soweit auf unseren Seiten personenbezogene Daten (beispielsweise Name,<br /> Anschrift oder eMail-Adressen) erhoben werden, erfolgt dies, soweit m&ouml;glich, stets auf freiwilliger Basis. Diese Daten werden ohne Ihre ausdr&uuml;ckliche Zustimmung nicht an Dritte weitergegeben.</p>
			<p>Wir weisen darauf hin, dass die Daten&uuml;bertragung im Internet (z.B.<br /> bei der Kommunikation per E-Mail) Sicherheitsl&uuml;cken aufweisen kann.<br /> Ein l&uuml;ckenloser Schutz der Daten vor dem Zugriff durch Dritte ist nicht<br /> m&ouml;glich.</p>
			<p>Der Nutzung von im Rahmen der Impressumspflicht ver&ouml;ffentlichten Kontaktdaten<br /> durch Dritte zur &Uuml;bersendung von nicht ausdr&uuml;cklich angeforderter<br /> Werbung und Informationsmaterialien wird hiermit ausdr&uuml;cklich widersprochen.<br /> Die Betreiber der Seiten behalten sich ausdr&uuml;cklich rechtliche Schritte<br /> im Falle der unverlangten Zusendung von Werbeinformationen, etwa durch Spam-Mails,<br /> vor.</p>
			<p>&nbsp;</p>
			<p><strong>Datenschutzerkl&auml;rung f&uuml;r die Nutzung von Facebook-Plugins<br /> (Like-Button)</strong></p>
			<p>Auf unseren Seiten sind Plugins des sozialen Netzwerks Facebook,<br /> 1601 South California Avenue, Palo Alto, CA 94304, USA integriert.<br /> Die Facebook-Plugins erkennen Sie an dem Facebook-Logo oder<br /> dem &ldquo;Like-Button&rdquo; (&ldquo;Gef&auml;llt mir&rdquo;) auf unserer Seite. Eine &Uuml;bersicht<br /> &uuml;ber die Facebook-Plugins finden Sie hier:<br /> <a href="http://developers.facebook.com/docs/plugins/">target=&rdquo;_blank&rdquo;&gt;http://developers.facebook.com/docs/plugins/</a>.<br /> Wenn Sie unsere Seiten<br /> besuchen, wird &uuml;ber das Plugin eine direkte Verbindung zwischen Ihrem<br /> Browser und dem Facebook-Server hergestellt. Facebook erh&auml;lt dadurch<br /> die Information, dass Sie mit Ihrer IP-Adresse unsere Seite<br /> besucht haben. Wenn Sie den Facebook &ldquo;Like-Button&rdquo; anklicken w&auml;hrend<br /> Sie in Ihrem Facebook-Account eingeloggt sind, k&ouml;nnen Sie die Inhalte<br /> unserer Seiten auf Ihrem Facebook-Profil verlinken. Dadurch kann<br /> Facebook den Besuch unserer Seiten Ihrem Benutzerkonto zuordnen. Wir<br /> weisen darauf hin, dass wir als Anbieter der Seiten keine Kenntnis vom<br /> Inhalt der &uuml;bermittelten Daten sowie deren Nutzung durch Facebook<br /> erhalten. Weitere Informationen hierzu finden Sie in der<br /> Datenschutzerkl&auml;rung von facebook unter</p>
			<p><a href="http://de-de.facebook.com/policy.php" target="_blank">http://de-de.facebook.com/policy.php</a></p>
			<p>Wenn Sie nicht w&uuml;nschen, dass Facebook den Besuch unserer Seiten Ihrem<br /> Facebook-Nutzerkonto zuordnen kann, loggen Sie sich bitte aus Ihrem<br /> Facebook-Benutzerkonto aus.</p>
			<p>&nbsp;</p>
			<p><strong>Datenschutzerkl&auml;rung f&uuml;r die Nutzung von Google Analytics</strong></p>
			<p>Diese Website benutzt Google Analytics, einen Webanalysedienst der Google Inc. (&ldquo;Google&rdquo;). Google Analytics verwendet sog. &ldquo;Cookies&rdquo;, Textdateien, die auf Ihrem Computer gespeichert werden und die eine Analyse der Benutzung der Website durch Sie erm&ouml;glichen. Die durch den Cookie erzeugten Informationen &uuml;ber Ihre Benutzung dieser Website werden in der Regel an einen Server von Google in den USA &uuml;bertragen und dort gespeichert. Im Falle der Aktivierung der IP-Anonymisierung auf dieser Webseite wird Ihre IP-Adresse von Google jedoch innerhalb von Mitgliedstaaten der Europ&auml;ischen Union oder in anderen Vertragsstaaten des Abkommens &uuml;ber den Europ&auml;ischen Wirtschaftsraum zuvor gek&uuml;rzt.</p>
			<p>Nur in Ausnahmef&auml;llen wird die volle IP-Adresse an einen Server von Google in den USA &uuml;bertragen und dort gek&uuml;rzt. Im Auftrag des Betreibers dieser Website wird Google diese Informationen benutzen, um Ihre Nutzung der Website auszuwerten, um Reports &uuml;ber die Websiteaktivit&auml;ten zusammenzustellen und um weitere mit der Websitenutzung und der Internetnutzung verbundene Dienstleistungen gegen&uuml;ber dem Websitebetreiber zu erbringen. Die im Rahmen von Google Analytics von Ihrem Browser &uuml;bermittelte IP-Adresse wird nicht mit anderen Daten von Google zusammengef&uuml;hrt.</p>
			<p>Sie k&ouml;nnen die Speicherung der Cookies durch eine entsprechende Einstellung Ihrer Browser-Software verhindern; wir weisen Sie jedoch darauf hin, dass Sie in diesem Fall gegebenenfalls nicht s&auml;mtliche Funktionen dieser Website vollumf&auml;nglich werden nutzen k&ouml;nnen. Sie k&ouml;nnen dar&uuml;ber hinaus die Erfassung der durch das Cookie erzeugten und auf Ihre Nutzung der Website bezogenen Daten (inkl. Ihrer IP-Adresse) an Google sowie die Verarbeitung dieser Daten durch Google verhindern, indem sie das unter dem folgenden Link verf&uuml;gbare Browser-Plugin herunterladen und installieren:<a href="http://tools.google.com/dlpage/gaoptout?hl=de">http://tools.google.com/dlpage/gaoptout?hl=de</a>.</p>
			<p>&nbsp;</p>
			<p><strong>Datenschutzerkl&auml;rung f&uuml;r die Nutzung von Google Adsense</strong></p>
			<p>Diese Website benutzt Google AdSense, einen Dienst zum Einbinden<br /> von Werbeanzeigen der Google Inc. (&ldquo;Google&rdquo;). Google AdSense<br /> verwendet sog. &ldquo;Cookies&rdquo;, Textdateien, die auf Ihrem Computer<br /> gespeichert werden und die eine Analyse der Benutzung der Website<br /> erm&ouml;glicht. Google AdSense verwendet auch so genannte Web Beacons<br /> (unsichtbare Grafiken). Durch diese Web Beacons k&ouml;nnen Informationen<br /> wie der Besucherverkehr auf diesen Seiten ausgewertet werden.</p>
			<p>Die durch Cookies und Web Beacons erzeugten Informationen &uuml;ber<br /> die Benutzung dieser Website (einschlie&szlig;lich Ihrer IP-Adresse) und<br /> Auslieferung von Werbeformaten werden an einen Server von Google<br /> in den USA &uuml;bertragen und dort gespeichert. Diese Informationen k&ouml;nnen<br /> von Google an Vertragspartner von Google weiter gegeben werden.<br /> Google wird Ihre IP-Adresse jedoch nicht mit anderen von Ihnen<br /> gespeicherten Daten zusammenf&uuml;hren.</p>
			<p>Sie k&ouml;nnen die Installation der Cookies durch eine entsprechende<br /> Einstellung Ihrer Browser Software verhindern; wir weisen Sie jedoch<br /> darauf hin, dass Sie in diesem Fall gegebenenfalls nicht s&auml;mtliche<br /> Funktionen dieser Website voll umf&auml;nglich nutzen k&ouml;nnen. Durch die<br /> Nutzung dieser Website erkl&auml;ren Sie sich mit der Bearbeitung der<br /> &uuml;ber Sie erhobenen Daten durch Google in der zuvor beschriebenen<br /> Art und Weise und zu dem zuvor benannten Zweck einverstanden.</p>
			<p>&nbsp;</p>
			<p><strong>Datenschutzerkl&auml;rung f&uuml;r die Nutzung von Google +1</strong></p>
			<p><em>Erfassung und Weitergabe von Informationen:</em><br /> Mithilfe der Google +1-Schaltfl&auml;che k&ouml;nnen Sie Informationen weltweit<br /> ver&ouml;ffentlichen. &uuml;ber die Google +1-Schaltfl&auml;che erhalten Sie und andere<br /> Nutzer personalisierte Inhalte von Google und unseren Partnern. Google<br /> speichert sowohl die Information, dass Sie f&uuml;r einen Inhalt +1 gegeben<br /> haben, als auch Informationen &uuml;ber die Seite, die Sie beim Klicken auf<br /> +1 angesehen haben. Ihre +1 k&ouml;nnen als Hinweise zusammen mit Ihrem<br /> Profilnamen und Ihrem Foto in Google-Diensten, wie etwa in<br /> Suchergebnissen oder in Ihrem Google-Profil, oder an anderen Stellen auf<br /> Websites und Anzeigen im Internet eingeblendet werden.<br /> Google zeichnet Informationen &uuml;ber Ihre +1-Aktivit&auml;ten auf, um die<br /> Google-Dienste f&uuml;r Sie und andere zu verbessern. Um die Google<br /> +1-Schaltfl&auml;che verwenden zu k&ouml;nnen, ben&ouml;tigen Sie ein weltweit<br /> sichtbares, &ouml;ffentliches Google-Profil, das zumindest den f&uuml;r das<br /> Profil gew&auml;hlten Namen enthalten muss. Dieser Name wird in allen<br /> Google-Diensten verwendet. In manchen F&auml;llen kann dieser Name auch<br /> einen anderen Namen ersetzen, den Sie beim Teilen von Inhalten &uuml;ber<br /> Ihr Google-Konto verwendet haben. Die Identit&auml;t Ihres Google-Profils<br /> kann Nutzern angezeigt werden, die Ihre E-Mail-Adresse kennen oder<br /> &uuml;ber andere identifizierende Informationen von Ihnen verf&uuml;gen.</p>
			<p><em>Verwendung der erfassten Informationen:</em><br /> Neben den oben erl&auml;uterten Verwendungszwecken werden die von Ihnen<br /> bereitgestellten Informationen gem&auml;&szlig; den geltenden<br /> Google-Datenschutzbestimmungen genutzt. Google ver&ouml;ffentlicht<br /> m&ouml;glicherweise zusammengefasste Statistiken &uuml;ber die +1-Aktivit&auml;ten<br /> der Nutzer bzw. gibt diese an Nutzer und Partner weiter, wie etwa<br /> Publisher, Inserenten oder verbundene Websites.</p>
			<p>&nbsp;</p>
			<p><strong>Datenschutzerkl&auml;rung f&uuml;r die Nutzung von Twitter</strong></p>
			<p>Auf unseren Seiten sind Funktionen des Dienstes Twitter eingebunden.<br /> Diese Funktionen werden angeboten durch die Twitter Inc., 795<br /> Folsom St., Suite 600, San Francisco, CA 94107, USA. Durch das Benutzen<br /> von Twitter und der Funktion &ldquo;Re-Tweet&rdquo; werden die von Ihnen<br /> besuchten Webseiten mit Ihrem Twitter-Account verkn&uuml;pft und anderen<br /> Nutzern bekannt gegeben. Dabei werden auch Daten an Twitter &uuml;bertragen.</p>
			<p>Wir weisen darauf hin, dass wir als Anbieter der Seiten keine<br /> Kenntnis vom Inhalt der &uuml;bermittelten Daten sowie deren Nutzung durch<br /> Twitter erhalten. Weitere Informationen hierzu finden Sie in der<br /> Datenschutzerkl&auml;rung von Twitter unter<br /> <a href="http://twitter.com/privacy" target="_blank">http://twitter.com/privacy</a>.</p>
			<p>Ihre Datenschutzeinstellungen bei Twitter k&ouml;nnen Sie in den<br /> Konto-Einstellungen unter<br /> <a href="http://twitter.com/account/settings" target="_blank">http://twitter.com/account/settings</a>&nbsp;&auml;ndern.</p></div>

		</div>

	</div>

<?php
	require_once("./template/content_post.php");
?>

